version: '3.7'
services:
  pharma:
    container_name: pharma
    image: pharma
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
    - 8080:8080
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: pharma
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
